Outlined Direct3D 11.0, able to get a basic device coded, but undefined reference to CreateDevice/CreateDevice and swap chain, probably need to swap the includes and libs for the SDK ones. I am going to file a bug report on the MinGW tracker.